name: Use Environment Variable

on:
  workflow_run:
    workflows: [ "Set Environment Variable" ]
    types:
      - completed

jobs:
  use-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use PR Version
        run: echo "The PR version is ${{ env.LATEST_VERSION }}"
