name: Use Environment Variable

on:
  workflow_run:
    workflows: [ "PR Title Checker" ]
    types:
      - completed

jobs:
  use-env-var:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version from build.gradle
        id: extract_version
        run: |
          version=$(grep '^version' build.gradle | sed 's/version[[:space:]]*=[[:space:]]*//;s/"//g')
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Build.gradle version: $version"
