name: Use Environment Variable

on:
  workflow_run:
    workflows: [ "Set Environment Variable" ]
    types:
      - completed

jobs:
  use-env-var:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub Variable
        uses: actions/github-script@v4
        with:
          script: |
            const { execSync } = require('child_process');
            const latestVersion = execSync('gh variable get LATEST_VERSION --body').toString().trim();
            console.log(`LATEST_VERSION=${latestVersion}`);
            execSync(`echo LATEST_VERSION=${latestVersion}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
